# yaml-language-server: $schema=./devcenter.schema.json

environmentTypes:
  - name: Dev
    tags:
      env: dev
  - name: Test
    tags:
      env: test
  - name: Prod
    tags:
      env: prod
catalogs:
  - name: Example
    repo: https://github.com/Azure/deployment-environments.git
    branch: main
    path: /Environments
projects:
  - name: Project-1
    members: []
    environmentTypes:
      - name: Dev
        deploymentTargetId: ""
        roles: ["Owner"]
        members: []
        tags:
          project: Project-1
      - name: Test
        deploymentTargetId: ""
        roles: ["Contributor"]
        members: []
        tags:
          project: Project-1
      - name: Prod
        deploymentTargetId: ""
        roles: ["Reader"]
        members: []
        tags:
          project: Project-1
  - name: Project-2
    members: []
    environmentTypes:
      - name: Dev
        deploymentTargetId: ""
        roles: ["Owner"]
        members: []
        tags:
          project: Project-2
      - name: Test
        deploymentTargetId: ""
        roles: ["Contributor"]
        members: []
        tags:
          project: Project-2
      - name: Prod
        deploymentTargetId: ""
        roles: ["Reader"]
        members: []
        tags:
          project: Project-2
